apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 600Mi
        - image: ghcr.io/jenkins-x/jx-boot:3.2.188
          name: add-new-var
          resources: {}
          script: |
            #!/usr/bin/env sh
            echo Newly added step
            echo export MYVAR='foo' >> .jx/variables.sh
            cat .jx/variables.sh
        - image: ghcr.io/jenkins-x/jx-boot:3.2.188
          name: access-new-var
          resources: {}
          script: |
            #!/usr/bin/env sh
            echo newly added step
            source .jx/variables.sh
            cat .jx/variables.sh
            echo ${MYVAR}
        - name: build-make-linux
          resources: {}
        - name: check-registry
          resources: {}
        - name: build-container-build
          resources: {}
        - name: promote-jx-preview
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
